package net.packet.abstr;

/**
 * All possible types of packets for communication between server & clients.
 *
 * @author tbuscher
 * @author tgeilen
 */
public enum PacketType {
  CHAT_MESSAGE_PACKET, CREATE_ACCOUNT_REQUEST_PACKET, CREATE_ACCOUNT_RESPONSE_PACKET,
  LOGIN_REQUEST_PACKET, LOGIN_RESPONSE_PACKET, INIT_SESSION_PACKET, PLAYER_ORDER_PACKET,
  UPDATE_ACCOUNT_REQUEST_PACKET, GAME_UPDATE_PACKET, REQUEST_TURN_PACKET, TURN_PACKET,
  GAME_START_PACKET, GAME_WIN_PACKET, ILLEGAL_TURN_PACKET, INIT_GAME_PACKET,
  CHECK_CONNECTION_PACKET, PLAYER_LIST_PACKET, RESTFUL_LOGIN_PACKET,
  DELETE_ACCOUNT_REQUEST_PACKET, HOST_QUIT_PACKET,
  PLAYER_QUIT_PACKET, PLAYER_KICK_PACKET, LOBBY_SCORE_BOARD_PACKET

}
